import json

seed_records = []

# ==========================================
# 1. COMPANIES (25 Records)
# ==========================================
companies = [
    {
        "entity_type": "Company",
        "name": "OpenAI",
        "description": "AI research and deployment company behind the GPT series, ChatGPT, DALL-E, and OpenAI o1 reasoning models.",
        "url": "https://openai.com",
        "categories": ["Large Language Models", "Generative AI", "AI Safety & Alignment"],
        "source": {"name": "Official Product Sites", "url": "https://openai.com/about"},
        "founding_year": 2015,
        "industry_sector": "Foundation Models & Artificial General Intelligence",
        "headquarters": "San Francisco, CA, USA",
        "valuation": "$157 Billion",
        "total_funding": "$17.9 Billion",
        "key_people": ["Sam Altman", "Greg Brockman", "Mira Murati"]
    },
    {
        "entity_type": "Company",
        "name": "Anthropic",
        "description": "AI safety and research company focused on building steerable, interpretable, and reliable frontier models including Claude 3.5.",
        "url": "https://anthropic.com",
        "categories": ["Large Language Models", "AI Safety & Alignment", "Autonomous Agents"],
        "source": {"name": "Official Product Sites", "url": "https://anthropic.com/company"},
        "founding_year": 2021,
        "industry_sector": "AI Safety & Frontier LLMs",
        "headquarters": "San Francisco, CA, USA",
        "valuation": "$40 Billion",
        "total_funding": "$9.7 Billion",
        "key_people": ["Dario Amodei", "Daniela Amodei", "Chris Olah"]
    },
    {
        "entity_type": "Company",
        "name": "Mistral AI",
        "description": "European AI lab developing open-weights and commercial frontier language models including Mistral Large and Codestral.",
        "url": "https://mistral.ai",
        "categories": ["Large Language Models", "Open Source AI", "Developer Tools"],
        "source": {"name": "Official Product Sites", "url": "https://mistral.ai/company"},
        "founding_year": 2023,
        "industry_sector": "Open Weights & Enterprise LLMs",
        "headquarters": "Paris, France",
        "valuation": "$6 Billion",
        "total_funding": "$1.1 Billion",
        "key_people": ["Arthur Mensch", "Guillaume Lample", "Timothée Lacroix"]
    },
    {
        "entity_type": "Company",
        "name": "Hugging Face",
        "description": "The open platform where the machine learning community collaborates on models, datasets, and AI applications.",
        "url": "https://huggingface.co",
        "categories": ["Open Source AI", "AI Infrastructure & Serving", "Developer Tools"],
        "source": {"name": "Official Product Sites", "url": "https://huggingface.co/about"},
        "founding_year": 2016,
        "industry_sector": "Open Source AI Hub & Infrastructure",
        "headquarters": "New York, NY, USA",
        "valuation": "$4.5 Billion",
        "total_funding": "$395 Million",
        "key_people": ["Clément Delangue", "Julien Chaumond", "Thomas Wolf"]
    },
    {
        "entity_type": "Company",
        "name": "Cohere",
        "description": "Enterprise AI platform specializing in enterprise-grade large language models, multilingual embeddings, and RAG solutions.",
        "url": "https://cohere.com",
        "categories": ["Large Language Models", "Retrieval-Augmented Generation", "Enterprise AI"],
        "source": {"name": "Official Product Sites", "url": "https://cohere.com/about"},
        "founding_year": 2019,
        "industry_sector": "Enterprise Search & Retrieval AI",
        "headquarters": "Toronto, Canada",
        "valuation": "$5.5 Billion",
        "total_funding": "$970 Million",
        "key_people": ["Aidan Gomez", "Nick Frosst", "Ivan Zhang"]
    },
    {
        "entity_type": "Company",
        "name": "DeepSeek",
        "description": "AI research lab known for high-efficiency open models such as DeepSeek-V3 and DeepSeek-R1 reasoning models.",
        "url": "https://deepseek.com",
        "categories": ["Large Language Models", "Open Source AI", "Reasoning Models"],
        "source": {"name": "Official Product Sites", "url": "https://deepseek.com"},
        "founding_year": 2023,
        "industry_sector": "High-Efficiency Frontier Open Models",
        "headquarters": "Hangzhou, China",
        "valuation": "$5 Billion",
        "total_funding": "Undisclosed",
        "key_people": ["Liang Wenfeng"]
    },
    {
        "entity_type": "Company",
        "name": "Google DeepMind",
        "description": "Pioneering AI research laboratory behind AlphaFold, AlphaGo, and Google Gemini multimodal frontier models.",
        "url": "https://deepmind.google",
        "categories": ["Large Language Models", "Multimodal AI", "Scientific AI"],
        "source": {"name": "Official Product Sites", "url": "https://deepmind.google/about"},
        "founding_year": 2010,
        "industry_sector": "Artificial General Intelligence & Frontier Multimodal Systems",
        "headquarters": "London, United Kingdom",
        "valuation": "Subsidiary of Alphabet",
        "total_funding": "$500 Million (Acquired)",
        "key_people": ["Demis Hassabis", "Shane Legg", "Jeff Dean"]
    },
    {
        "entity_type": "Company",
        "name": "Meta",
        "description": "Technology conglomerate leading open-source foundation model research with the Llama series and PyTorch ecosystem.",
        "url": "https://ai.meta.com",
        "categories": ["Open Source AI", "Large Language Models", "Computer Vision"],
        "source": {"name": "Official Product Sites", "url": "https://ai.meta.com/about"},
        "founding_year": 2004,
        "industry_sector": "Open Source Foundation Models & Social AI",
        "headquarters": "Menlo Park, CA, USA",
        "valuation": "$1.4 Trillion",
        "total_funding": "Public (NASDAQ: META)",
        "key_people": ["Mark Zuckerberg", "Yann LeCun", "Joelle Pineau"]
    },
    {
        "entity_type": "Company",
        "name": "NVIDIA",
        "description": "Global leader in accelerated computing hardware, GPUs (H100, Blackwell), and AI enterprise software frameworks (CUDA, NeMo, TensorRT-LLM).",
        "url": "https://nvidia.com",
        "categories": ["AI Hardware & Accelerators", "AI Infrastructure & Serving"],
        "source": {"name": "Official Product Sites", "url": "https://nvidia.com/about"},
        "founding_year": 1993,
        "industry_sector": "AI Accelerators, Silicon & Enterprise Software",
        "headquarters": "Santa Clara, CA, USA",
        "valuation": "$3.2 Trillion",
        "total_funding": "Public (NASDAQ: NVDA)",
        "key_people": ["Jensen Huang", "Ian Buck", "Bill Dally"]
    },
    {
        "entity_type": "Company",
        "name": "Figure AI",
        "description": "Autonomous humanoid robotics company creating general-purpose bipedal robots for manufacturing, logistics, and human assistance.",
        "url": "https://figure.ai",
        "categories": ["Robotics & Embodied AI", "Autonomous Agents"],
        "source": {"name": "Official Product Sites", "url": "https://figure.ai/about"},
        "founding_year": 2022,
        "industry_sector": "General-Purpose Humanoid Robotics",
        "headquarters": "Sunnyvale, CA, USA",
        "valuation": "$2.6 Billion",
        "total_funding": "$675 Million",
        "key_people": ["Brett Adcock", "Jerry Pratt", "Kyle Vogt"]
    },
    {
        "entity_type": "Company",
        "name": "Boston Dynamics",
        "description": "World leader in dynamic mobile robotics, creators of the Atlas electric humanoid, Spot quadruped, and Stretch warehouse robot.",
        "url": "https://bostondynamics.com",
        "categories": ["Robotics & Embodied AI"],
        "source": {"name": "Official Product Sites", "url": "https://bostondynamics.com/about"},
        "founding_year": 1992,
        "industry_sector": "Dynamic Mobile & Humanoid Robotics",
        "headquarters": "Waltham, MA, USA",
        "valuation": "$1.1 Billion (Hyundai subsidiary)",
        "total_funding": "Acquired",
        "key_people": ["Robert Playter", "Marc Raibert"]
    },
    {
        "entity_type": "Company",
        "name": "Unitree Robotics",
        "description": "Robotics enterprise developing high-performance commercial bipedal humanoid robots (G1, H1) and quadruped platforms.",
        "url": "https://unitree.com",
        "categories": ["Robotics & Embodied AI", "AI Hardware & Accelerators"],
        "source": {"name": "Official Product Sites", "url": "https://unitree.com"},
        "founding_year": 2016,
        "industry_sector": "Consumer & Industrial Mobile Robotics",
        "headquarters": "Hangzhou, China",
        "valuation": "$1.2 Billion",
        "total_funding": "$140 Million",
        "key_people": ["Xingxing Wang"]
    },
    {
        "entity_type": "Company",
        "name": "1X Technologies",
        "description": "AI and robotics company producing androids designed to work alongside humans, including NEO and EVE bipedal/wheeled robots.",
        "url": "https://1x.tech",
        "categories": ["Robotics & Embodied AI", "Autonomous Agents"],
        "source": {"name": "Official Product Sites", "url": "https://1x.tech/about"},
        "founding_year": 2014,
        "industry_sector": "Safe Embodied Androids for Home & Work",
        "headquarters": "Moss, Norway & Sunnyvale, CA",
        "valuation": "$800 Million",
        "total_funding": "$125 Million",
        "key_people": ["Bernt Børnich"]
    },
    {
        "entity_type": "Company",
        "name": "Sanctuary AI",
        "description": "Creators of Phoenix, a general-purpose humanoid robot powered by the Carbon cognitive architecture for human-like intelligence.",
        "url": "https://sanctuary.ai",
        "categories": ["Robotics & Embodied AI", "Autonomous Agents"],
        "source": {"name": "Official Product Sites", "url": "https://sanctuary.ai/about"},
        "founding_year": 2018,
        "industry_sector": "Cognitive Humanoid Robotics",
        "headquarters": "Vancouver, Canada",
        "valuation": "$500 Million",
        "total_funding": "$140 Million",
        "key_people": ["Geordie Rose", "Suzanne Gildert", "Olivia Norton"]
    },
    {
        "entity_type": "Company",
        "name": "ElevenLabs",
        "description": "Voice AI research company delivering lifelike text-to-speech, voice cloning, and real-time conversational voice agents.",
        "url": "https://elevenlabs.io",
        "categories": ["Audio & Speech", "Generative AI", "Creative AI & Generation"],
        "source": {"name": "Official Product Sites", "url": "https://elevenlabs.io/about"},
        "founding_year": 2022,
        "industry_sector": "Voice AI & Audio Synthesis",
        "headquarters": "New York, NY, USA",
        "valuation": "$3.3 Billion",
        "total_funding": "$180 Million",
        "key_people": ["Piotr Dabkowski", "Mati Staniszewski"]
    },
    {
        "entity_type": "Company",
        "name": "Runway",
        "description": "Applied AI research company pioneering multimodal generative AI systems and foundational video models including Gen-3 Alpha.",
        "url": "https://runwayml.com",
        "categories": ["Creative AI & Generation", "Computer Vision", "Generative AI"],
        "source": {"name": "Official Product Sites", "url": "https://runwayml.com/about"},
        "founding_year": 2018,
        "industry_sector": "Cinematic Generative Video & Creative Tools",
        "headquarters": "New York, NY, USA",
        "valuation": "$1.5 Billion",
        "total_funding": "$237 Million",
        "key_people": ["Cristóbal Valenzuela", "Anastasis Germanidis", "Alejandro Matamala"]
    },
    {
        "entity_type": "Company",
        "name": "Midjourney",
        "description": "Independent research lab focused on expanding the imaginative powers of the human species through text-to-image synthesis.",
        "url": "https://midjourney.com",
        "categories": ["Creative AI & Generation", "Generative AI", "Computer Vision"],
        "source": {"name": "Official Product Sites", "url": "https://midjourney.com"},
        "founding_year": 2021,
        "industry_sector": "Image Synthesis & Creative AI",
        "headquarters": "San Francisco, CA, USA",
        "valuation": "$10 Billion (Bootstrapped)",
        "total_funding": "Self-Funded",
        "key_people": ["David Holz"]
    },
    {
        "entity_type": "Company",
        "name": "Cursor",
        "description": "The AI-first code editor built by Anysphere to supercharge developer productivity with deep codebase understanding.",
        "url": "https://cursor.com",
        "categories": ["Developer Tools", "Autonomous Agents"],
        "source": {"name": "Official Product Sites", "url": "https://cursor.com/about"},
        "founding_year": 2022,
        "industry_sector": "AI Integrated Development Environments",
        "headquarters": "San Francisco, CA, USA",
        "valuation": "$2.5 Billion",
        "total_funding": "$68 Million",
        "key_people": ["Michael Truell", "Sualeh Asif", "Arvid Lunnemark", "Aman Sanger"]
    },
    {
        "entity_type": "Company",
        "name": "Groq",
        "description": "Compute company creator of the LPU (Language Processing Unit) inference engine for ultra-low latency real-time LLM serving.",
        "url": "https://groq.com",
        "categories": ["AI Hardware & Accelerators", "AI Infrastructure & Serving"],
        "source": {"name": "Official Product Sites", "url": "https://groq.com/about"},
        "founding_year": 2016,
        "industry_sector": "Real-Time AI Inference Silicon",
        "headquarters": "Mountain View, CA, USA",
        "valuation": "$2.8 Billion",
        "total_funding": "$640 Million",
        "key_people": ["Jonathan Ross", "Stuart Pann"]
    },
    {
        "entity_type": "Company",
        "name": "Scale AI",
        "description": "Data infrastructure platform providing data annotation, RLHF, and evaluation for frontier AI labs and enterprises.",
        "url": "https://scale.com",
        "categories": ["AI Infrastructure & Serving", "Enterprise AI"],
        "source": {"name": "Official Product Sites", "url": "https://scale.com/about"},
        "founding_year": 2016,
        "industry_sector": "Data Labeling, RLHF & Model Evaluation",
        "headquarters": "San Francisco, CA, USA",
        "valuation": "$13.8 Billion",
        "total_funding": "$1.6 Billion",
        "key_people": ["Alexandr Wang", "Lucy Guo"]
    },
    {
        "entity_type": "Company",
        "name": "Perplexity AI",
        "description": "AI conversational search engine that delivers accurate, real-time cited answers to complex queries.",
        "url": "https://perplexity.ai",
        "categories": ["Personal AI Assistants", "Retrieval-Augmented Generation", "Generative AI"],
        "source": {"name": "Official Product Sites", "url": "https://perplexity.ai/about"},
        "founding_year": 2022,
        "industry_sector": "Conversational Search & Knowledge Discovery",
        "headquarters": "San Francisco, CA, USA",
        "valuation": "$9 Billion",
        "total_funding": "$165 Million",
        "key_people": ["Aravind Srinivas", "Denis Yarats", "Johnny Ho", "Andy Konwinski"]
    },
    {
        "entity_type": "Company",
        "name": "Rabbit",
        "description": "AI hardware startup developing pocket-sized companion devices and Large Action Models (LAM) to interact with mobile apps.",
        "url": "https://rabbit.tech",
        "categories": ["AI Hardware & Accelerators", "Autonomous Agents", "Personal AI Assistants"],
        "source": {"name": "Official Product Sites", "url": "https://rabbit.tech/about"},
        "founding_year": 2023,
        "industry_sector": "AI Consumer Hardware & Action Models",
        "headquarters": "Santa Monica, CA, USA",
        "valuation": "$300 Million",
        "total_funding": "$36 Million",
        "key_people": ["Jesse Lyu"]
    },
    {
        "entity_type": "Company",
        "name": "Humane",
        "description": "Experience company designing wearable AI devices, ambient computing platforms, and screenless personal assistants.",
        "url": "https://hu.ma.ne",
        "categories": ["AI Hardware & Accelerators", "Personal AI Assistants"],
        "source": {"name": "Official Product Sites", "url": "https://hu.ma.ne/about"},
        "founding_year": 2018,
        "industry_sector": "Wearable AI & Ambient Computing",
        "headquarters": "San Francisco, CA, USA",
        "valuation": "$850 Million",
        "total_funding": "$230 Million",
        "key_people": ["Imran Chaudhri", "Bethany Bongiorno"]
    },
    {
        "entity_type": "Company",
        "name": "Cerebras Systems",
        "description": "Creator of the Wafer-Scale Engine (WSE-3), building ultra-scale compute clusters for accelerated deep learning and inference.",
        "url": "https://cerebras.ai",
        "categories": ["AI Hardware & Accelerators", "AI Infrastructure & Serving"],
        "source": {"name": "Official Product Sites", "url": "https://cerebras.ai/about"},
        "founding_year": 2016,
        "industry_sector": "Wafer-Scale AI Accelerators & Supercomputing",
        "headquarters": "Sunnyvale, CA, USA",
        "valuation": "$8 Billion",
        "total_funding": "$750 Million",
        "key_people": ["Andrew Feldman", "Gary Lauterbach", "Sean Lie"]
    },
    {
        "entity_type": "Company",
        "name": "Stability AI",
        "description": "Open-source generative AI company creator of Stable Diffusion image and video synthesis foundation models.",
        "url": "https://stability.ai",
        "categories": ["Creative AI & Generation", "Open Source AI", "Computer Vision"],
        "source": {"name": "Official Product Sites", "url": "https://stability.ai/about"},
        "founding_year": 2020,
        "industry_sector": "Open Foundation Models for Media Generation",
        "headquarters": "London, United Kingdom",
        "valuation": "$1 Billion",
        "total_funding": "$173 Million",
        "key_people": ["Prem Akkaraju", "Sean Shannon"]
    }
]

seed_records.extend(companies)

print(f"Added {len(companies)} Companies. Total: {len(seed_records)}")
